name: Trigger auto deployment for container-app-zu7khvpv75gkc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-zu7khvpv75gkc-AutoDeployTrigger-daa73500-0dcb-4059-95fe-a8d41dfb83c8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZU7KHVPV75GKC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZU7KHVPV75GKC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZU7KHVPV75GKC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPZU7KHVPV75GKC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZU7KHVPV75GKC_REGISTRY_PASSWORD }}
          containerAppName: container-app-zu7khvpv75gkc
          resourceGroup: appspacesfastapi8558bc6a
          imageToBuild: default/container-app-zu7khvpv75gkc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


